[build]
  base    = "frontend"
  command = "npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_BACKEND_URL    = "https://flourish123-production.up.railway.app"
  REACT_APP_FRONTEND_URL   = "https://theflourishapp.netlify.app"
  REACT_APP_EMAILJS_SERVICE_ID  = "service_j42my6w"
  REACT_APP_EMAILJS_TEMPLATE_ID = "template_n6z3imq"
  REACT_APP_EMAILJS_PUBLIC_KEY  = "DR-sqj6t_mREKLmE8"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
